from typing import Any, Dict, List

# Each dictionary defines a scenario by specifying its differences from the base configuration (in run_experiments.py).
scenarios: List[Dict[str, Any]] = [
     # # ==============================================================================
    # # --- IID Scenarios ---
    # # ==============================================================================
    {
        "scenario_name": "FedAvg_IID",
        "strategy-name": "fedprox",
        "proximal-mu": 0.0,
        "partitioner-name": "iid",
    },
    # {
    #     "scenario_name": "FedProx_IID",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.01,
    #     "partitioner-name": "iid",
    # },
    # {
    #     "scenario_name": "FedAvgM_IID",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "iid",
    # },
    # {
    #     "scenario_name": "FedAdam_IID",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.7,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "iid",
    # },
    # {
    #     "scenario_name": "FedYogi_IID",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.7,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "iid",
    # },
# ==============================================================================
    # --- FedAvg with Central DP in IID scenarios ---
    # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_IID_DP_noise03",  
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "use_dp": True,
    #     "dp_noise_multiplier": 0.0,
    #     "dp_clipping_norm": 100000,
    #     "fraction-train": 0.5,
    #     "fraction-evaluate": 0.5,
    # },
    # ==============================================================================
    # --- Backdoor Attack Scenarios (non-IID, alpha=0.1, 1 malicious node) ---
    # ==============================================================================
    # {
    #     "scenario_name": "Backdoor_Attack_FedAvg_nonIID_a01",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15, 
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_FedTrimmedAvg_nonIID_a01",
    #     "strategy-name": "trimmed_avg",
    #     "beta": 0.2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5],
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_FedMedian_nonIID_a01",
    #     "strategy-name": "median",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_MultiKrum_nonIID_a01",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5], 
    #     "num-malicious-nodes": 2, 
    #     "num_nodes_to_select": 8,
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # ==============================================================================
    # --- Backdoor Attack Scenarios (IID, 1 malicious node) ---
    # ==============================================================================
    # {
    #     "scenario_name": "Backdoor_Attack_FedAvg_IID",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15, 
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_FedTrimmedAvg_IID",
    #     "strategy-name": "trimmed_avg",
    #     "beta": 0.2,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5],
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # {      
    #     "scenario_name": "Backdoor_Attack_FedMedian_IID",
    #     "strategy-name": "median",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_MultiKrum_IID",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5], 
    #     "num-malicious-nodes": 2, 
    #     "num_nodes_to_select": 8,
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # ==============================================================================
    # --- Backdoor Attack Scenarios (non-IID, alpha=0.5, 1 malicious node) ---
    # ==============================================================================
    # {
    #     "scenario_name": "Backdoor_Attack_FedAvg_nonIID_a05",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3], 
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15, 
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_FedTrimmedAvg_nonIID_a05",
    #     "strategy-name": "trimmed_avg",
    #     "beta": 0.2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3],
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_FedMedian_nonIID_a05",
    #     "strategy-name": "median",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3], 
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
    # {
    #     "scenario_name": "Backdoor_Attack_MultiKrum_nonIID_a05",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3], 
    #     "num-malicious-nodes": 1, 
    #     "num_nodes_to_select": 9,
    #     "attack_name": "backdoor",
    #     "attack_target_class": 1,
    #     "attack_injection_rate": 0.15,
    # },
   # ==============================================================================
    # --- Label Flipping Attack Scenarios (IID, 3 malicious nodes) ---
    # ==============================================================================
    # {
    #     "scenario_name": "LabelFlip_Attack_FedAvg_IID",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5, 7],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedTrimmedAvg_IID",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.3,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5, 7],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedMedian_IID",
    #     "strategy-name": "median",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5, 7],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_MultiKrum_IID",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5, 7],
    #     "num-malicious-nodes": 3, 
    #     "num_nodes_to_select": 7,
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },

    # # ==============================================================================
    # # --- Label Flipping Attack Scenarios (non-IID, alpha=0.1, 3 malicious nodes) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "LabelFlip_Attack_FedAvg_nonIID_a01",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5, 7], 
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedTrimmedAvg_nonIID_a01",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5, 7], 
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedMedian_nonIID_a01",
    #     "strategy-name": "median",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5, 7],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_MultiKrum_nonIID_a01",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5, 7],
    #     "num-malicious-nodes": 3,
    #     "num_nodes_to_select": 7,
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
       # ==============================================================================
    # --- Label Flipping Attack Scenarios (IID, 1 malicious nodes) ---
    # ==============================================================================
    # {
    #     "scenario_name": "LabelFlip_Attack_FedAvg_IID",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedTrimmedAvg_IID",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.1,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedMedian_IID",
    #     "strategy-name": "median",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_MultiKrum_IID",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3],
    #     "num-malicious-nodes": 1, 
    #     "num_nodes_to_select": 9,
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },

    # # ==============================================================================
    # # --- Label Flipping Attack Scenarios (non-IID, alpha=0.1, 1 malicious nodes) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "LabelFlip_Attack_FedAvg_nonIID_a01",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3], 
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedTrimmedAvg_nonIID_a01",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.1,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3], 
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedMedian_nonIID_a01",
    #     "strategy-name": "median",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_MultiKrum_nonIID_a01",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3],
    #     "num-malicious-nodes": 1,
    #     "num_nodes_to_select": 9,
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },

    # # # ==============================================================================
    # # # --- Label Flipping Attack Scenarios (non-IID, alpha=0.5, 2 malicious nodes) ---
    # # # ==============================================================================
    # {
    #     "scenario_name": "LabelFlip_Attack_FedAvg_nonIID_a05",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedTrimmedAvg_nonIID_a05",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_FedMedian_nonIID_a05",
    #     "strategy-name": "median",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5],
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },
    # {
    #     "scenario_name": "LabelFlip_Attack_MultiKrum_nonIID_a05",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5],
    #     "num-malicious-nodes": 2,
    #     "num_nodes_to_select": 8,
    #     "attack_name": "label_flipping",
    #     "attack_flip-fraction": 1.0,
    # },

    # ==============================================================================
    # --- Byzantine Attack Scenarios (IID, 2 malicious nodes) ---
    # ==============================================================================
    # {
    #     "scenario_name": "Byzantine_Attack_FedAvg_IID",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_FedTrimmedAvg_IID",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.2,
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_FedMedian_IID",
    #     "strategy-name": "median",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5],
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_MultiKrum_IID",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "iid",
    #     "malicious-clients-ids": [3, 5],
    #     "num-malicious-nodes": 2, 
    #     "num_nodes_to_select": 8,
    #     "attack_name": "byzantine",
    # },

    # ==============================================================================
    # --- Byzantine Attack Scenarios (non-IID, alpha=0.1, 2 malicious nodes) ---
    # ==============================================================================
    # {
    #     "scenario_name": "Byzantine_Attack_FedAvg_nonIID_a01",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_FedTrimmedAvg_nonIID_a01",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_FedMedian_nonIID_a01",
    #     "strategy-name": "median",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5],
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_MultiKrum_nonIID_a01",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "malicious-clients-ids": [3, 5],
    #     "num-malicious-nodes": 2,
    #     "num_nodes_to_select": 8,
    #     "attack_name": "byzantine",
    # },

     # ==============================================================================
    # --- Byzantine Attack Scenarios (non-IID, alpha=0.5, 2 malicious nodes) ---
    # ==============================================================================
    # {
    #     "scenario_name": "Byzantine_Attack_FedAvg_nonIID_a05",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_FedTrimmedAvg_nonIID_a05",
    #     "strategy-name": "trimmed_avg", 
    #     "beta": 0.2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5], 
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_FedMedian_nonIID_a05",
    #     "strategy-name": "median",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5],
    #     "attack_name": "byzantine",
    # },
    # {
    #     "scenario_name": "Byzantine_Attack_MultiKrum_nonIID_a05",
    #     "strategy-name": "multikrum",
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "malicious-clients-ids": [3, 5],
    #     "num-malicious-nodes": 2,
    #     "num_nodes_to_select": 8,
    #     "attack_name": "byzantine",
    # },
    # ==============================================================================
    # --- Non-IID Scenarios (alpha=0.1) ---
    # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_1",
    #     "strategy-name": "fedprox", # FedProx with proximal-mu: 0.0 acts as FedAvg
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    # },
    # {
    #     "scenario_name": "FedProx_nonIID_a0_1",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.01,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_1",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_1",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_1",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    # },
 # ==============================================================================
    # --- Non-IID Scenarios (alpha=0.03) ---
    # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_03",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    # },
    # {
    #     "scenario_name": "FedProx_nonIID_a0_03",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.01,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_03",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_03",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_03",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    # },
   
    # # ==============================================================================
    # # --- Non-IID Scenarios (alpha=0.5) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_5",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    # },
    # {
    #     "scenario_name": "FedProx_nonIID_a0_5",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.01,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_5",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_5",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.7,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_5",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.7,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    # },
    # # ==============================================================================
    # # --- Personalization Scenarios (FedPer) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_1_personalized",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "personalization": True,
    # },
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_5_personalized",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "personalization": True,
    # },
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_03_personalized",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "personalization": True,
    # },
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_03_personalized_frac08", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "personalization": True,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    #     {
    #     "scenario_name": "FedAvg_nonIID_a0_03_personalized_frac07", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "personalization": True,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_5_personalized_frac08", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "personalization": True,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    #  {
    #     "scenario_name": "FedAvg_nonIID_a0_5_personalized_frac07", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "personalization": True,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # },
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_1_personalized_frac08", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "personalization": True,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    #  {
    #     "scenario_name": "FedAvg_nonIID_a0_1_personalized_frac07", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "personalization": True,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAvg_IID_personalized_frac08",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "personalization": True,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedAvg_IID_personalized_frac07",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "personalization": True,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAvg_IID_personalized",
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "iid",
    #     "personalization": True,
    # },

# # ==============================================================================
    # # --- Partial Participation (fraction: 0.8) - Non-IID Scenarios (alpha=0.03) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_03_frac08", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_03_frac08",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_03_frac08",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_03_frac08",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # # # ==============================================================================
    # # # --- Partial Participation (fraction: 0.7) - Non-IID Scenarios (alpha=0.03) ---
    # # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_03_frac07", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_03_frac07",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_03_frac07",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_03_frac07",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.03,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },

# # ==============================================================================
    # # --- Partial Participation (fraction: 0.8) - Non-IID Scenarios (alpha=0.1) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_1_frac08", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_1_frac08",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_1_frac08",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_1_frac08",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # # ==============================================================================
    # # --- Partial Participation (fraction: 0.7) - Non-IID Scenarios (alpha=0.1) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_1_frac07", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_1_frac07",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_1_frac07",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_1_frac07",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.1,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
     # # ==============================================================================
    # # --- Partial Participation (fraction: 0.8) - Non-IID Scenarios (alpha=0.5) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_5_frac08", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_5_frac08",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_5_frac08",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_5_frac08",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.8,
    #     "fraction-evaluate": 0.8,
    # },
# # ==============================================================================
    # # --- Partial Participation (fraction: 0.7) - Non-IID Scenarios (alpha=0.5) ---
    # # ==============================================================================
    # {
    #     "scenario_name": "FedAvg_nonIID_a0_5_frac07", 
    #     "strategy-name": "fedprox",
    #     "proximal-mu": 0.0,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAvgM_nonIID_a0_5_frac07",
    #     "strategy-name": "fedavgm",
    #     "server_learning_rate": 1.0,
    #     "server_momentum": 0.7,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedAdam_nonIID_a0_5_frac07",
    #     "strategy-name": "fedadam",
    #     "eta": 1e-1,
    #     "eta_l": 1e-1,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-2,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
    # {
    #     "scenario_name": "FedYogi_nonIID_a0_5_frac07",
    #     "strategy-name": "fedyogi",
    #     "eta": 1e-2,
    #     "eta_l": 0.0316,
    #     "beta_1": 0.70,
    #     "beta_2": 0.99,
    #     "tau": 1e-3,
    #     "partitioner-name": "dirichlet",
    #     "dirichlet-alpha": 0.5,
    #     "fraction-train": 0.7,
    #     "fraction-evaluate": 0.7,
    # },
]